/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMealDialog: typeof import('./src/components/AddMealDialog.vue')['default']
    AddRestaurantDialog: typeof import('./src/components/AddRestaurantDialog.vue')['default']
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    DeleteMealDialog: typeof import('./src/components/DeleteMealDialog.vue')['default']
    EditMealDialog: typeof import('./src/components/EditMealDialog.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ErrorDialog: typeof import('./src/components/ErrorDialog.vue')['default']
    OrderDetailDialog: typeof import('./src/components/OrderDetailDialog.vue')['default']
    RateOrderDialog: typeof import('./src/components/RateOrderDialog.vue')['default']
    RestaurantSidebar: typeof import('./src/components/RestaurantSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SuccessAlert: typeof import('./src/components/SuccessAlert.vue')['default']
    SuccessDialog: typeof import('./src/components/successDialog.vue')['default']
    WarningDialog: typeof import('./src/components/WarningDialog.vue')['default']
    WorkerSidebar: typeof import('./src/components/WorkerSidebar.vue')['default']
  }
}
